services:
  db:
    image: mysql:8.0
    container_name: lernt-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: lernt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
